
import { Injectable } from '@nestjs/common';
import { SqlTemplate } from './entities/sql-template.entity';

@Injectable()
export class SqlApiDocService {
    generateOpenApiSpec(template: SqlTemplate) {
        const properties: any = {};
        const required: string[] = [];

        if (template.parameters) {
            template.parameters.forEach(p => {
                const typeMap = {
                    'string': 'string',
                    'number': 'number',
                    'boolean': 'boolean',
                    'date': 'string' // ISO Date
                };

                properties[p.name] = {
                    type: typeMap[p.type] || 'string',
                    description: `Parameter: ${p.name}`
                };

                if (p.required) required.push(p.name);
            });
        }

        // Add API Key param
        properties['apiKey'] = { type: 'string', description: 'Your unique API Key' };
        required.push('apiKey');

        // Add Template ID param
        properties['templateId'] = { type: 'string', default: template.id, readOnly: true };
        required.push('templateId');

        return {
            openapi: '3.0.0',
            info: {
                title: template.name,
                description: template.description || 'Dynamic SQL API generated by Jainsight',
                version: '1.0.0'
            },
            servers: [
                { url: process.env.PUBLIC_URL || 'http://localhost:3000', description: 'API Server' }
            ],
            paths: {
                '/api/sql-api/execute': {
                    post: {
                        summary: `Execute ${template.name}`,
                        description: template.description,
                        operationId: 'executeSql',
                        requestBody: {
                            required: true,
                            content: {
                                'application/json': {
                                    schema: {
                                        type: 'object',
                                        properties: {
                                            params: {
                                                type: 'object',
                                                properties: properties,
                                                required: required.filter(r => r !== 'apiKey' && r !== 'templateId')
                                            },
                                            apiKey: { type: 'string' },
                                            templateId: { type: 'string', default: template.id }
                                        },
                                        required: ['apiKey', 'templateId']
                                    }
                                }
                            }
                        },
                        responses: {
                            '200': {
                                description: 'Query Results',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                rows: { type: 'array', items: { type: 'object' } },
                                                fields: { type: 'array', items: { type: 'string' } },
                                                rowCount: { type: 'number' }
                                            }
                                        }
                                    }
                                }
                            },
                            '400': { description: 'Validation Error' },
                            '401': { description: 'Invalid API Key' }
                        }
                    }
                }
            }
        };
    }
}
