
import { Injectable } from '@nestjs/common';
import { SqlTemplate } from './entities/sql-template.entity';

@Injectable()
export class SqlApiDocService {
    generateOpenApiSpec(template: SqlTemplate) {
        const properties: any = {};
        const required: string[] = [];

        if (template.parameters) {
            template.parameters.forEach(p => {
                const typeMap: Record<string, string> = {
                    'string': 'string',
                    'number': 'number',
                    'boolean': 'boolean',
                    'date': 'string' // ISO Date
                };

                properties[p.name] = {
                    type: typeMap[p.type] || 'string',
                    description: `Parameter: ${p.name}`,
                    ...(p.defaultValue !== undefined && { default: p.defaultValue }),
                };

                if (p.required) required.push(p.name);
            });
        }

        // Add API Key param
        properties['apiKey'] = { type: 'string', description: 'Your unique API Key' };
        required.push('apiKey');

        // Build deprecation notice
        const deprecationNotice = template.deprecatedAt
            ? `\n\n⚠️ **DEPRECATED**: ${template.deprecatedMessage || 'This API has been deprecated.'}`
            : '';

        // Build rate limit info
        const rateLimitInfo = template.rateLimit
            ? `\n\n📊 **Rate Limit**: ${template.rateLimit.requests} requests per ${template.rateLimit.windowSeconds} seconds`
            : '';

        // Build cache info
        const cacheInfo = template.cacheTtl
            ? `\n\n💾 **Cache TTL**: ${template.cacheTtl} seconds`
            : '';

        // Build tags
        const tags = template.tags?.length ? template.tags : ['sql-api'];

        // Example values for parameters
        const exampleParams: Record<string, any> = {};
        template.parameters?.forEach(p => {
            if (p.defaultValue !== undefined) {
                exampleParams[p.name] = p.defaultValue;
            } else {
                exampleParams[p.name] = p.type === 'number' ? 123 
                    : p.type === 'boolean' ? true 
                    : p.type === 'date' ? '2024-01-01' 
                    : 'example_value';
            }
        });

        return {
            openapi: '3.0.3',
            info: {
                title: template.name,
                description: `${template.description || 'Dynamic SQL API generated by Jainsight'}${deprecationNotice}${rateLimitInfo}${cacheInfo}`,
                version: `${template.version || 1}.0.0`,
                ...(template.deprecatedAt && { 'x-deprecated': true }),
            },
            servers: [
                { url: process.env.PUBLIC_URL || 'http://localhost:3000', description: 'API Server' }
            ],
            tags: [
                { name: 'sql-api', description: 'SQL API Execution Endpoints' },
                ...tags.filter(t => t !== 'sql-api').map(t => ({ name: t, description: `Tag: ${t}` })),
            ],
            paths: {
                [`/api/sql-api/execute/${template.id}`]: {
                    post: {
                        summary: `Execute ${template.name}`,
                        description: template.description,
                        operationId: `execute_${template.id.replace(/-/g, '_')}`,
                        tags: tags,
                        ...(template.deprecatedAt && { deprecated: true }),
                        requestBody: {
                            required: true,
                            content: {
                                'application/json': {
                                    schema: {
                                        type: 'object',
                                        properties: {
                                            params: {
                                                type: 'object',
                                                properties: properties,
                                                required: required.filter(r => r !== 'apiKey')
                                            },
                                            apiKey: { type: 'string', description: 'Your unique API Key' },
                                        },
                                        required: ['apiKey']
                                    },
                                    example: {
                                        apiKey: template.apiKey,
                                        params: exampleParams,
                                    }
                                }
                            }
                        },
                        responses: {
                            '200': {
                                description: 'Query Results',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                rows: { type: 'array', items: { type: 'object' } },
                                                fields: { type: 'array', items: { type: 'string' } },
                                                rowCount: { type: 'integer' }
                                            }
                                        },
                                        example: {
                                            rows: [{ id: 1, name: 'Example' }],
                                            fields: ['id', 'name'],
                                            rowCount: 1
                                        }
                                    }
                                },
                                ...(template.rateLimit && {
                                    headers: {
                                        'X-RateLimit-Limit': {
                                            description: 'Rate limit requests per window',
                                            schema: { type: 'integer' }
                                        },
                                        'X-RateLimit-Remaining': {
                                            description: 'Remaining requests in current window',
                                            schema: { type: 'integer' }
                                        },
                                        'X-RateLimit-Reset': {
                                            description: 'Timestamp when the rate limit resets',
                                            schema: { type: 'integer' }
                                        }
                                    }
                                })
                            },
                            '400': {
                                description: 'Validation Error - Missing or invalid parameters',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                statusCode: { type: 'integer', example: 400 },
                                                message: { type: 'string', example: 'Missing required parameter: userId' },
                                                error: { type: 'string', example: 'Bad Request' }
                                            }
                                        }
                                    }
                                }
                            },
                            '401': {
                                description: 'Invalid or missing API Key',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                statusCode: { type: 'integer', example: 401 },
                                                message: { type: 'string', example: 'Invalid API Key' },
                                                error: { type: 'string', example: 'Unauthorized' }
                                            }
                                        }
                                    }
                                }
                            },
                            '403': {
                                description: 'API is disabled or deprecated',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                statusCode: { type: 'integer', example: 403 },
                                                message: { type: 'string', example: 'API is currently disabled' },
                                                error: { type: 'string', example: 'Forbidden' }
                                            }
                                        }
                                    }
                                }
                            },
                            '404': {
                                description: 'API Template not found',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                statusCode: { type: 'integer', example: 404 },
                                                message: { type: 'string', example: 'Template not found' },
                                                error: { type: 'string', example: 'Not Found' }
                                            }
                                        }
                                    }
                                }
                            },
                            '429': {
                                description: 'Rate limit exceeded',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                statusCode: { type: 'integer', example: 429 },
                                                message: { type: 'string', example: 'ThrottlerException: Too Many Requests' },
                                                error: { type: 'string', example: 'Too Many Requests' }
                                            }
                                        }
                                    }
                                },
                                headers: {
                                    'Retry-After': {
                                        description: 'Seconds to wait before retrying',
                                        schema: { type: 'integer' }
                                    }
                                }
                            },
                            '500': {
                                description: 'Internal Server Error - Query execution failed',
                                content: {
                                    'application/json': {
                                        schema: {
                                            type: 'object',
                                            properties: {
                                                statusCode: { type: 'integer', example: 500 },
                                                message: { type: 'string', example: 'Query execution failed' },
                                                error: { type: 'string', example: 'Internal Server Error' }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        security: [{ apiKey: [] }]
                    }
                }
            },
            components: {
                securitySchemes: {
                    apiKey: {
                        type: 'apiKey',
                        in: 'body',
                        name: 'apiKey',
                        description: 'API Key for authentication'
                    }
                }
            }
        };
    }

    // Generate a Postman collection for the API
    generatePostmanCollection(template: SqlTemplate) {
        const baseUrl = process.env.PUBLIC_URL || 'http://localhost:3000';
        
        const exampleParams: Record<string, any> = {};
        template.parameters?.forEach(p => {
            exampleParams[p.name] = p.defaultValue !== undefined ? p.defaultValue
                : p.type === 'number' ? 123
                : p.type === 'boolean' ? true
                : 'example_value';
        });

        return {
            info: {
                _postman_id: template.id,
                name: `${template.name} API`,
                description: template.description || 'Generated by Jainsight SQL-to-API Gateway',
                schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
            },
            item: [
                {
                    name: `Execute ${template.name}`,
                    request: {
                        method: 'POST',
                        header: [
                            {
                                key: 'Content-Type',
                                value: 'application/json'
                            }
                        ],
                        body: {
                            mode: 'raw',
                            raw: JSON.stringify({
                                apiKey: template.apiKey,
                                params: exampleParams
                            }, null, 2)
                        },
                        url: {
                            raw: `${baseUrl}/api/sql-api/execute/${template.id}`,
                            protocol: baseUrl.startsWith('https') ? 'https' : 'http',
                            host: [baseUrl.replace(/https?:\/\//, '').split(':')[0]],
                            port: baseUrl.includes(':') ? baseUrl.split(':').pop()?.split('/')[0] : undefined,
                            path: ['api', 'sql-api', 'execute', template.id]
                        }
                    },
                    response: []
                }
            ],
            variable: [
                {
                    key: 'baseUrl',
                    value: baseUrl
                },
                {
                    key: 'apiKey',
                    value: template.apiKey
                }
            ]
        };
    }
}
